# Generated by Django 5.0.6 on 2024-07-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_server_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='server_id',
        ),
    ]
